import type { Metadata } from "next";
import './globals.css';

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="h-full flex flex-col">
            <body
                className={`${inter.className} antialiased flex flex-col flex-1 items-center justify-center`}
            >
                {children}
            </body>
        </html>
    );
}
